if(Bookmarks.find().count()===0)
{
    Bookmarks.insert({
        name:'百度',
        url:'http://www.baidu.com'
    });
    Bookmarks.insert({
        name:'淘宝',
        url:'http://www.taobao.com'
    });
    Bookmarks.insert({
        name:'腾讯',
        url:'http://www.qq.com'
    });
}